const cwd = __dirname

module.exports = {
  apps: [
    {
      name: 'toppath-server',
      cwd,
      script: 'dist-server/server/index.js',
      watch: false,
      windowsHide: true,
      autorestart: true,
      max_memory_restart: '800M',
      max_restarts: 10,
      restart_delay: 3000,
      env: {
        NODE_ENV: 'production',
        PORT: '3000',
        WORKER_URL: 'http://127.0.0.1:3010',
      },
      out_file: './logs/pm2-server-out.log',
      error_file: './logs/pm2-server-error.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'toppath-worker',
      cwd,
      script: 'dist-server/server/worker.js',
      watch: false,
      windowsHide: true,
      autorestart: true,
      max_memory_restart: '700M',
      cron_restart: '0 4 * * *',
      max_restarts: 20,
      restart_delay: 3000,
      node_args: '--max-old-space-size=640',
      env: {
        NODE_ENV: 'production',
        WORKER_PORT: '3010',
        WORKER_BROWSER_CONCURRENCY: '2',
        WORKER_AI_CONCURRENCY: '1',
        WORKER_BATCH_CONCURRENCY: '1',
      },
      out_file: './logs/pm2-worker-out.log',
      error_file: './logs/pm2-worker-error.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'toppath-tunnel',
      cwd,
      script: 'ngrok',
      args: 'http 3000 --url https://royal-parched-catcall.ngrok-free.dev',
      interpreter: 'none',
      watch: false,
      windowsHide: true,
      autorestart: true,
      max_memory_restart: '300M',
      max_restarts: 10,
      restart_delay: 5000,
      out_file: './logs/pm2-tunnel-out.log',
      error_file: './logs/pm2-tunnel-error.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
  ],
}
